import 'package:islami_application/models/sura_data_model.dart';

abstract class Constants {
  List<String> arabicQuranSurasNames = [
    "الفاتحه",
    "البقرة",
    "آل عمران",
    "النساء",
    "المائدة",
    "الأنعام",
    "الأعراف",
    "الأنفال",
    "التوبة",
    "يونس",
    "هود",
    "يوسف",
    "الرعد",
    "إبراهيم",
    "الحجر",
    "النحل",
    "الإسراء",
    "الكهف",
    "مريم",
    "طه",
    "الأنبياء",
    "الحج",
    "المؤمنون",
    "النّور",
    "الفرقان",
    "الشعراء",
    "النّمل",
    "القصص",
    "العنكبوت",
    "الرّوم",
    "لقمان",
    "السجدة",
    "الأحزاب",
    "سبأ",
    "فاطر",
    "يس",
    "الصافات",
    "ص",
    "الزمر",
    "غافر",
    "فصّلت",
    "الشورى",
    "الزخرف",
    "الدّخان",
    "الجاثية",
    "الأحقاف",
    "محمد",
    "الفتح",
    "الحجرات",
    "ق",
    "الذاريات",
    "الطور",
    "النجم",
    "القمر",
    "الرحمن",
    "الواقعة",
    "الحديد",
    "المجادلة",
    "الحشر",
    "الممتحنة",
    "الصف",
    "الجمعة",
    "المنافقون",
    "التغابن",
    "الطلاق",
    "التحريم",
    "الملك",
    "القلم",
    "الحاقة",
    "المعارج",
    "نوح",
    "الجن",
    "المزّمّل",
    "المدّثر",
    "القيامة",
    "الإنسان",
    "المرسلات",
    "النبأ",
    "النازعات",
    "عبس",
    "التكوير",
    "الإنفطار",
    "المطفّفين",
    "الإنشقاق",
    "البروج",
    "الطارق",
    "الأعلى",
    "الغاشية",
    "الفجر",
    "البلد",
    "الشمس",
    "الليل",
    "الضحى",
    "الشرح",
    "التين",
    "العلق",
    "القدر",
    "البينة",
    "الزلزلة",
    "العاديات",
    "القارعة",
    "التكاثر",
    "العصر",
    "الهمزة",
    "الفيل",
    "قريش",
    "الماعون",
    "الكوثر",
    "الكافرون",
    "النصر",
    "المسد",
    "الإخلاص",
    "الفلق",
    "الناس",
  ];
  List<String> englishQuranSurasNames = [
    "Al-Fatiha",
    "Al-Baqarah",
    "Aal-E-Imran",
    "An-Nisa'",
    "Al-Ma'idah",
    "Al-An'am",
    "Al-A'raf",
    "Al-Anfal",
    "At-Tawbah",
    "Yunus",
    "Hud",
    "Yusuf",
    "Ar-Ra'd",
    "Ibrahim",
    "Al-Hijr",
    "An-Nahl",
    "Al-Isra",
    "Al-Kahf",
    "Maryam",
    "Ta-Ha",
    "Al-Anbiya",
    "Al-Hajj",
    "Al-Mu'minun",
    "An-Nur",
    "Al-Furqan",
    "Ash-Shu'ara",
    "An-Naml",
    "Al-Qasas",
    "Al-Ankabut",
    "Ar-Rum",
    "Luqman",
    "As-Sajda",
    "Al-Ahzab",
    "Saba",
    "Fatir",
    "Ya-Sin",
    "As-Saffat",
    "Sad",
    "Az-Zumar",
    "Ghafir",
    "Fussilat",
    "Ash-Shura",
    "Az-Zukhruf",
    "Ad-Dukhan",
    "Al-Jathiya",
    "Al-Ahqaf",
    "Muhammad",
    "Al-Fath",
    "Al-Hujurat",
    "Qaf",
    "Adh-Dhariyat",
    "At-Tur",
    "An-Najm",
    "Al-Qamar",
    "Ar-Rahman",
    "Al-Waqi'a",
    "Al-Hadid",
    "Al-Mujadila",
    "Al-Hashr",
    "Al-Mumtahina",
    "As-Saff",
    "Al-Jumu'a",
    "Al-Munafiqun",
    "At-Taghabun",
    "At-Talaq",
    "At-Tahrim",
    "Al-Mulk",
    "Al-Qalam",
    "Al-Haqqah",
    "Al-Ma'arij",
    "Nuh",
    "Al-Jinn",
    "Al-Muzzammil",
    "Al-Muddathir",
    "Al-Qiyamah",
    "Al-Insan",
    "Al-Mursalat",
    "An-Naba'",
    "An-Nazi'at",
    "Abasa",
    "At-Takwir",
    "Al-Infitar",
    "Al-Mutaffifin",
    "Al-Inshiqaq",
    "Al-Buruj",
    "At-Tariq",
    "Al-A'la",
    "Al-Ghashiyah",
    "Al-Fajr",
    "Al-Balad",
    "Ash-Shams",
    "Al-Lail",
    "Ad-Duha",
    "Ash-Sharh",
    "At-Tin",
    "Al-Alaq",
    "Al-Qadr",
    "Al-Bayyina",
    "Az-Zalzalah",
    "Al-Adiyat",
    "Al-Qari'a",
    "At-Takathur",
    "Al-Asr",
    "Al-Humazah",
    "Al-Fil",
    "Quraysh",
    "Al-Ma'un",
    "Al-Kawthar",
    "Al-Kafirun",
    "An-Nasr",
    "Al-Masad",
    "Al-Ikhlas",
    "Al-Falaq",
    "An-Nas",
  ];
  List<String> AyaNumbers = [
    '7',
    '286',
    '200',
    '176',
    '120',
    '165',
    '206',
    '75',
    '129',
    '109',
    '123',
    '111',
    '43',
    '52',
    '99',
    '128',
    '111',
    '110',
    '98',
    '135',
    '112',
    '78',
    '118',
    '64',
    '77',
    '227',
    '93',
    '88',
    '69',
    '60',
    '34',
    '30',
    '73',
    '54',
    '45',
    '83',
    '182',
    '88',
    '75',
    '85',
    '54',
    '53',
    '89',
    '59',
    '37',
    '35',
    '38',
    '29',
    '18',
    '45',
    '60',
    '49',
    '62',
    '55',
    '78',
    '96',
    '29',
    '22',
    '24',
    '13',
    '14',
    '11',
    '11',
    '18',
    '12',
    '12',
    '30',
    '52',
    '52',
    '44',
    '28',
    '28',
    '20',
    '56',
    '40',
    '31',
    '50',
    '40',
    '46',
    '42',
    '29',
    '19',
    '36',
    '25',
    '22',
    '17',
    '19',
    '26',
    '30',
    '20',
    '15',
    '21',
    '11',
    '8',
    '5',
    '19',
    '5',
    '8',
    '8',
    '11',
    '11',
    '8',
    '3',
    '9',
    '5',
    '4',
    '6',
    '3',
    '6',
    '3',
    '5',
    '4',
    '5',
    '6',
  ];

  static List<SuraDataModel> suraDataList = [
    SuraDataModel(
      suraID: "1",
      suraNameAR: "الفاتحة",
      suraNameEN: "Al-Fatiha",
      suraVersesNumbers: "7",
    ),
    SuraDataModel(
      suraID: "2",
      suraNameAR: "البقرة",
      suraNameEN: "Al-Baqara",
      suraVersesNumbers: "286",
    ),
    SuraDataModel(
      suraID: "3",
      suraNameAR: "آل عمران",
      suraNameEN: "Aal-E-Imran",
      suraVersesNumbers: "200",
    ),
    SuraDataModel(
      suraID: "4",
      suraNameAR: "النساء",
      suraNameEN: "An-Nisa",
      suraVersesNumbers: "176",
    ),
    SuraDataModel(
      suraID: "5",
      suraNameAR: "المائدة",
      suraNameEN: "Al-Ma'idah",
      suraVersesNumbers: "120",
    ),
    SuraDataModel(
      suraID: "6",
      suraNameAR: "الأنعام",
      suraNameEN: "Al-An'am",
      suraVersesNumbers: "165",
    ),
    SuraDataModel(
      suraID: "7",
      suraNameAR: "الأعراف",
      suraNameEN: "Al-A'raf",
      suraVersesNumbers: "206",
    ),
    SuraDataModel(
      suraID: "8",
      suraNameAR: "الأنفال",
      suraNameEN: "Al-Anfal",
      suraVersesNumbers: "75",
    ),
    SuraDataModel(
      suraID: "9",
      suraNameAR: "التوبة",
      suraNameEN: "At-Tawbah",
      suraVersesNumbers: "129",
    ),
    SuraDataModel(
      suraID: "10",
      suraNameAR: "يونس",
      suraNameEN: "Yunus",
      suraVersesNumbers: "109",
    ),
    SuraDataModel(
      suraID: "11",
      suraNameAR: "هود",
      suraNameEN: "Hud",
      suraVersesNumbers: "123",
    ),
    SuraDataModel(
      suraID: "12",
      suraNameAR: "يوسف",
      suraNameEN: "Yusuf",
      suraVersesNumbers: "111",
    ),
    SuraDataModel(
      suraID: "13",
      suraNameAR: "الرعد",
      suraNameEN: "Ar-Ra'd",
      suraVersesNumbers: "43",
    ),
    SuraDataModel(
      suraID: "14",
      suraNameAR: "إبراهيم",
      suraNameEN: "Ibrahim",
      suraVersesNumbers: "52",
    ),
    SuraDataModel(
      suraID: "15",
      suraNameAR: "الحجر",
      suraNameEN: "Al-Hijr",
      suraVersesNumbers: "99",
    ),
    SuraDataModel(
      suraID: "16",
      suraNameAR: "النحل",
      suraNameEN: "An-Nahl",
      suraVersesNumbers: "128",
    ),
    SuraDataModel(
      suraID: "17",
      suraNameAR: "الإسراء",
      suraNameEN: "Al-Isra",
      suraVersesNumbers: "111",
    ),
    SuraDataModel(
      suraID: "18",
      suraNameAR: "الكهف",
      suraNameEN: "Al-Kahf",
      suraVersesNumbers: "110",
    ),
    SuraDataModel(
      suraID: "19",
      suraNameAR: "مريم",
      suraNameEN: "Maryam",
      suraVersesNumbers: "98",
    ),
    SuraDataModel(
      suraID: "20",
      suraNameAR: "طه",
      suraNameEN: "Ta-Ha",
      suraVersesNumbers: "135",
    ),
    SuraDataModel(
      suraID: "21",
      suraNameAR: "الأنبياء",
      suraNameEN: "Al-Anbiya",
      suraVersesNumbers: "112",
    ),
    SuraDataModel(
      suraID: "22",
      suraNameAR: "الحج",
      suraNameEN: "Al-Hajj",
      suraVersesNumbers: "78",
    ),
    SuraDataModel(
      suraID: "23",
      suraNameAR: "المؤمنون",
      suraNameEN: "Al-Mu'minun",
      suraVersesNumbers: "118",
    ),
    SuraDataModel(
      suraID: "24",
      suraNameAR: "النور",
      suraNameEN: "An-Nur",
      suraVersesNumbers: "64",
    ),
    SuraDataModel(
      suraID: "25",
      suraNameAR: "الفرقان",
      suraNameEN: "Al-Furqan",
      suraVersesNumbers: "77",
    ),
    SuraDataModel(
      suraID: "26",
      suraNameAR: "الشعراء",
      suraNameEN: "Ash-Shu'ara",
      suraVersesNumbers: "227",
    ),
    SuraDataModel(
      suraID: "27",
      suraNameAR: "النمل",
      suraNameEN: "An-Naml",
      suraVersesNumbers: "93",
    ),
    SuraDataModel(
      suraID: "28",
      suraNameAR: "القصص",
      suraNameEN: "Al-Qasas",
      suraVersesNumbers: "88",
    ),
    SuraDataModel(
      suraID: "29",
      suraNameAR: "العنكبوت",
      suraNameEN: "Al-Ankabut",
      suraVersesNumbers: "69",
    ),
    SuraDataModel(
      suraID: "30",
      suraNameAR: "الروم",
      suraNameEN: "Ar-Rum",
      suraVersesNumbers: "60",
    ),
    SuraDataModel(
      suraID: "31",
      suraNameAR: "لقمان",
      suraNameEN: "Luqman",
      suraVersesNumbers: "34",
    ),
    SuraDataModel(
      suraID: "32",
      suraNameAR: "السجدة",
      suraNameEN: "As-Sajda",
      suraVersesNumbers: "30",
    ),
    SuraDataModel(
      suraID: "33",
      suraNameAR: "الأحزاب",
      suraNameEN: "Al-Ahzab",
      suraVersesNumbers: "73",
    ),
    SuraDataModel(
      suraID: "34",
      suraNameAR: "سبإ",
      suraNameEN: "Saba",
      suraVersesNumbers: "54",
    ),
    SuraDataModel(
      suraID: "35",
      suraNameAR: "فاطر",
      suraNameEN: "Fatir",
      suraVersesNumbers: "45",
    ),
    SuraDataModel(
      suraID: "36",
      suraNameAR: "يس",
      suraNameEN: "Ya-Sin",
      suraVersesNumbers: "83",
    ),
    SuraDataModel(
      suraID: "37",
      suraNameAR: "الصافات",
      suraNameEN: "As-Saffat",
      suraVersesNumbers: "182",
    ),
    SuraDataModel(
      suraID: "38",
      suraNameAR: "ص",
      suraNameEN: "Sad",
      suraVersesNumbers: "88",
    ),
    SuraDataModel(
      suraID: "39",
      suraNameAR: "الزمر",
      suraNameEN: "Az-Zumar",
      suraVersesNumbers: "75",
    ),
    SuraDataModel(
      suraID: "40",
      suraNameAR: "غافر",
      suraNameEN: "Ghafir",
      suraVersesNumbers: "85",
    ),
    SuraDataModel(
      suraID: "41",
      suraNameAR: "فصلت",
      suraNameEN: "Fussilat",
      suraVersesNumbers: "54",
    ),
    SuraDataModel(
      suraID: "42",
      suraNameAR: "الشورى",
      suraNameEN: "Ash-Shura",
      suraVersesNumbers: "53",
    ),
    SuraDataModel(
      suraID: "43",
      suraNameAR: "الزخرف",
      suraNameEN: "Az-Zukhruf",
      suraVersesNumbers: "89",
    ),
    SuraDataModel(
      suraID: "44",
      suraNameAR: "الدخان",
      suraNameEN: "Ad-Dukhan",
      suraVersesNumbers: "59",
    ),
    SuraDataModel(
      suraID: "45",
      suraNameAR: "الجاثية",
      suraNameEN: "Al-Jathiya",
      suraVersesNumbers: "37",
    ),
    SuraDataModel(
      suraID: "46",
      suraNameAR: "الأحقاف",
      suraNameEN: "Al-Ahqaf",
      suraVersesNumbers: "35",
    ),
    SuraDataModel(
      suraID: "47",
      suraNameAR: "محمد",
      suraNameEN: "Muhammad",
      suraVersesNumbers: "38",
    ),
    SuraDataModel(
      suraID: "48",
      suraNameAR: "الفتح",
      suraNameEN: "Al-Fath",
      suraVersesNumbers: "29",
    ),
    SuraDataModel(
      suraID: "49",
      suraNameAR: "الحجرات",
      suraNameEN: "Al-Hujurat",
      suraVersesNumbers: "18",
    ),
    SuraDataModel(
      suraID: "50",
      suraNameAR: "ق",
      suraNameEN: "Qaf",
      suraVersesNumbers: "45",
    ),
    SuraDataModel(
      suraID: "51",
      suraNameAR: "الذاريات",
      suraNameEN: "Adh-Dhariyat",
      suraVersesNumbers: "60",
    ),
    SuraDataModel(
      suraID: "52",
      suraNameAR: "الطور",
      suraNameEN: "At-Tur",
      suraVersesNumbers: "49",
    ),
    SuraDataModel(
      suraID: "53",
      suraNameAR: "النجم",
      suraNameEN: "An-Najm",
      suraVersesNumbers: "62",
    ),
    SuraDataModel(
      suraID: "54",
      suraNameAR: "القمر",
      suraNameEN: "Al-Qamar",
      suraVersesNumbers: "55",
    ),
    SuraDataModel(
      suraID: "55",
      suraNameAR: "الرحمن",
      suraNameEN: "Ar-Rahman",
      suraVersesNumbers: "78",
    ),
    SuraDataModel(
      suraID: "56",
      suraNameAR: "الواقعة",
      suraNameEN: "Al-Waqi'a",
      suraVersesNumbers: "96",
    ),
    SuraDataModel(
      suraID: "57",
      suraNameAR: "الحديد",
      suraNameEN: "Al-Hadid",
      suraVersesNumbers: "29",
    ),
    SuraDataModel(
      suraID: "58",
      suraNameAR: "المجادلة",
      suraNameEN: "Al-Mujadila",
      suraVersesNumbers: "22",
    ),
    SuraDataModel(
      suraID: "59",
      suraNameAR: "الحشر",
      suraNameEN: "Al-Hashr",
      suraVersesNumbers: "24",
    ),
    SuraDataModel(
      suraID: "60",
      suraNameAR: "الممتحنة",
      suraNameEN: "Al-Mumtahina",
      suraVersesNumbers: "13",
    ),
    SuraDataModel(
      suraID: "61",
      suraNameAR: "الصف",
      suraNameEN: "As-Saff",
      suraVersesNumbers: "14",
    ),
    SuraDataModel(
      suraID: "62",
      suraNameAR: "الجمعة",
      suraNameEN: "Al-Jumu'a",
      suraVersesNumbers: "11",
    ),
    SuraDataModel(
      suraID: "63",
      suraNameAR: "المنافقون",
      suraNameEN: "Al-Munafiqun",
      suraVersesNumbers: "11",
    ),
    SuraDataModel(
      suraID: "64",
      suraNameAR: "التغابن",
      suraNameEN: "At-Taghabun",
      suraVersesNumbers: "18",
    ),
    SuraDataModel(
      suraID: "65",
      suraNameAR: "الطلاق",
      suraNameEN: "At-Talaq",
      suraVersesNumbers: "12",
    ),
    SuraDataModel(
      suraID: "66",
      suraNameAR: "التحريم",
      suraNameEN: "At-Tahrim",
      suraVersesNumbers: "12",
    ),
    SuraDataModel(
      suraID: "67",
      suraNameAR: "الملك",
      suraNameEN: "Al-Mulk",
      suraVersesNumbers: "30",
    ),
    SuraDataModel(
      suraID: "68",
      suraNameAR: "القلم",
      suraNameEN: "Al-Qalam",
      suraVersesNumbers: "52",
    ),
    SuraDataModel(
      suraID: "69",
      suraNameAR: "الحاقة",
      suraNameEN: "Al-Haqqah",
      suraVersesNumbers: "52",
    ),
    SuraDataModel(
      suraID: "70",
      suraNameAR: "المعارج",
      suraNameEN: "Al-Ma'arij",
      suraVersesNumbers: "44",
    ),
    SuraDataModel(
      suraID: "71",
      suraNameAR: "نوح",
      suraNameEN: "Nuh",
      suraVersesNumbers: "28",
    ),
    SuraDataModel(
      suraID: "72",
      suraNameAR: "الجن",
      suraNameEN: "Al-Jinn",
      suraVersesNumbers: "28",
    ),
    SuraDataModel(
      suraID: "73",
      suraNameAR: "المزمل",
      suraNameEN: "Al-Muzzammil",
      suraVersesNumbers: "20",
    ),
    SuraDataModel(
      suraID: "74",
      suraNameAR: "المدثر",
      suraNameEN: "Al-Muddathir",
      suraVersesNumbers: "56",
    ),
    SuraDataModel(
      suraID: "75",
      suraNameAR: "القيامة",
      suraNameEN: "Al-Qiyama",
      suraVersesNumbers: "40",
    ),
    SuraDataModel(
      suraID: "76",
      suraNameAR: "الإنسان",
      suraNameEN: "Al-Insan",
      suraVersesNumbers: "31",
    ),
    SuraDataModel(
      suraID: "77",
      suraNameAR: "المرسلات",
      suraNameEN: "Al-Mursalat",
      suraVersesNumbers: "50",
    ),
    SuraDataModel(
      suraID: "78",
      suraNameAR: "النبأ",
      suraNameEN: "An-Naba",
      suraVersesNumbers: "40",
    ),
    SuraDataModel(
      suraID: "79",
      suraNameAR: "النازعات",
      suraNameEN: "An-Nazi'at",
      suraVersesNumbers: "46",
    ),
    SuraDataModel(
      suraID: "80",
      suraNameAR: "عبس",
      suraNameEN: "Abasa",
      suraVersesNumbers: "42",
    ),
    SuraDataModel(
      suraID: "81",
      suraNameAR: "التكوير",
      suraNameEN: "At-Takwir",
      suraVersesNumbers: "29",
    ),
    SuraDataModel(
      suraID: "82",
      suraNameAR: "الانفطار",
      suraNameEN: "Al-Infitar",
      suraVersesNumbers: "19",
    ),
    SuraDataModel(
      suraID: "83",
      suraNameAR: "المطففين",
      suraNameEN: "Al-Mutaffifin",
      suraVersesNumbers: "36",
    ),
    SuraDataModel(
      suraID: "84",
      suraNameAR: "الانشقاق",
      suraNameEN: "Al-Inshiqaq",
      suraVersesNumbers: "25",
    ),
    SuraDataModel(
      suraID: "85",
      suraNameAR: "البروج",
      suraNameEN: "Al-Buruj",
      suraVersesNumbers: "22",
    ),
    SuraDataModel(
      suraID: "86",
      suraNameAR: "الطارق",
      suraNameEN: "At-Tariq",
      suraVersesNumbers: "17",
    ),
    SuraDataModel(
      suraID: "87",
      suraNameAR: "الأعلى",
      suraNameEN: "Al-A'la",
      suraVersesNumbers: "19",
    ),
    SuraDataModel(
      suraID: "88",
      suraNameAR: "الغاشية",
      suraNameEN: "Al-Ghashiyah",
      suraVersesNumbers: "26",
    ),
    SuraDataModel(
      suraID: "89",
      suraNameAR: "الفجر",
      suraNameEN: "Al-Fajr",
      suraVersesNumbers: "30",
    ),
    SuraDataModel(
      suraID: "90",
      suraNameAR: "البلد",
      suraNameEN: "Al-Balad",
      suraVersesNumbers: "20",
    ),
    SuraDataModel(
      suraID: "91",
      suraNameAR: "الشمس",
      suraNameEN: "Ash-Shams",
      suraVersesNumbers: "15",
    ),
    SuraDataModel(
      suraID: "92",
      suraNameAR: "الليل",
      suraNameEN: "Al-Lail",
      suraVersesNumbers: "21",
    ),
    SuraDataModel(
      suraID: "93",
      suraNameAR: "الضحى",
      suraNameEN: "Ad-Duhaa",
      suraVersesNumbers: "11",
    ),
    SuraDataModel(
      suraID: "94",
      suraNameAR: "الشرح",
      suraNameEN: "Ash-Sharh",
      suraVersesNumbers: "8",
    ),
    SuraDataModel(
      suraID: "95",
      suraNameAR: "التين",
      suraNameEN: "At-Tin",
      suraVersesNumbers: "8",
    ),
    SuraDataModel(
      suraID: "96",
      suraNameAR: "العلق",
      suraNameEN: "Al-Alaq",
      suraVersesNumbers: "19",
    ),
    SuraDataModel(
      suraID: "97",
      suraNameAR: "القدر",
      suraNameEN: "Al-Qadr",
      suraVersesNumbers: "5",
    ),
    SuraDataModel(
      suraID: "98",
      suraNameAR: "البينة",
      suraNameEN: "Al-Bayyina",
      suraVersesNumbers: "8",
    ),
    SuraDataModel(
      suraID: "99",
      suraNameAR: "الزلزلة",
      suraNameEN: "Az-Zalzalah",
      suraVersesNumbers: "8",
    ),
    SuraDataModel(
      suraID: "100",
      suraNameAR: "العاديات",
      suraNameEN: "Al-Adiyat",
      suraVersesNumbers: "11",
    ),
    SuraDataModel(
      suraID: "101",
      suraNameAR: "القارعة",
      suraNameEN: "Al-Qari'a",
      suraVersesNumbers: "11",
    ),
    SuraDataModel(
      suraID: "102",
      suraNameAR: "التكاثر",
      suraNameEN: "At-Takathur",
      suraVersesNumbers: "8",
    ),
    SuraDataModel(
      suraID: "103",
      suraNameAR: "العصر",
      suraNameEN: "Al-Asr",
      suraVersesNumbers: "3",
    ),
    SuraDataModel(
      suraID: "104",
      suraNameAR: "الهمزة",
      suraNameEN: "Al-Humazah",
      suraVersesNumbers: "9",
    ),
    SuraDataModel(
      suraID: "105",
      suraNameAR: "الفيل",
      suraNameEN: "Al-Fil",
      suraVersesNumbers: "5",
    ),
    SuraDataModel(
      suraID: "106",
      suraNameAR: "قريش",
      suraNameEN: "Quraysh",
      suraVersesNumbers: "4",
    ),
    SuraDataModel(
      suraID: "107",
      suraNameAR: "الماعون",
      suraNameEN: "Al-Ma'un",
      suraVersesNumbers: "7",
    ),
    SuraDataModel(
      suraID: "108",
      suraNameAR: "الكوثر",
      suraNameEN: "Al-Kawthar",
      suraVersesNumbers: "3",
    ),
    SuraDataModel(
      suraID: "109",
      suraNameAR: "الكافرون",
      suraNameEN: "Al-Kafirun",
      suraVersesNumbers: "6",
    ),
    SuraDataModel(
      suraID: "110",
      suraNameAR: "النصر",
      suraNameEN: "An-Nasr",
      suraVersesNumbers: "3",
    ),
    SuraDataModel(
      suraID: "111",
      suraNameAR: "المسد",
      suraNameEN: "Al-Masad",
      suraVersesNumbers: "5",
    ),
    SuraDataModel(
      suraID: "112",
      suraNameAR: "الإخلاص",
      suraNameEN: "Al-Ikhlas",
      suraVersesNumbers: "4",
    ),
    SuraDataModel(
      suraID: "113",
      suraNameAR: "الفلق",
      suraNameEN: "Al-Falaq",
      suraVersesNumbers: "5",
    ),
    SuraDataModel(
      suraID: "114",
      suraNameAR: "الناس",
      suraNameEN: "An-Nas",
      suraVersesNumbers: "6",
    ),
  ];
}
